apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpc-db-storage
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mpc-db-pass
type: Opaque
stringData:
  password: "super-secret-password-123"