apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mpc-db
spec:
  serviceName: "mpc-db"
  replicas: 1
  selector:
    matchLabels:
      app: mpc-db
  template:
    metadata:
      labels:
        app: mpc-db
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mpc-db-pass
              key: password
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi